version: "3.9"
networks:
  app-tier:
    driver: bridge
services:
  ansible:
    image: williamyeh/ansible:centos7
    volumes:
      - "./ansible-learning/ssh/config:/root/.ssh/config"
      - "./ansible-learning/hosts/hosts:/etc/ansible/hosts"
      - "./ansible-learning/playbooks:/root/playbooks"
    links:
      - server

  server:
    build: .
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/home/jovyan
    ports: 
      - "8888:8888"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 8080:8080
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123test
    ports:
      - '15672:15672'
    networks:
      - app-tier
    
volumes:
  pgdata: